// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ahlatciapp.Context;

#nullable disable

namespace ahlatciapp.Migrations
{
    [DbContext(typeof(AhlContext))]
    [Migration("20230808205708_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ahlatciapp.Models.AboneAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AboneKsBilgiId")
                        .HasColumnType("int");

                    b.Property<string>("Bina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaddeSok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mahalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("İl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("İlce")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AboneKsBilgiId")
                        .IsUnique();

                    b.ToTable("AboneAdres");
                });

            modelBuilder.Entity("ahlatciapp.Models.AboneKsBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnneKizlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoyTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KmlFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meslek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SağlıkDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoyAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uyruk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboneBilgi");
                });

            modelBuilder.Entity("ahlatciapp.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AboneKsBilgiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FaturaKesimTarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("M3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AboneKsBilgiId");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("ahlatciapp.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PrAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrAdı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrSifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrSoyAdı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrTcNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrTel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personel");
                });

            modelBuilder.Entity("ahlatciapp.Models.AboneAdres", b =>
                {
                    b.HasOne("ahlatciapp.Models.AboneKsBilgi", "abone")
                        .WithOne("adresler")
                        .HasForeignKey("ahlatciapp.Models.AboneAdres", "AboneKsBilgiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abone");
                });

            modelBuilder.Entity("ahlatciapp.Models.Fatura", b =>
                {
                    b.HasOne("ahlatciapp.Models.AboneKsBilgi", "Abone")
                        .WithMany("faturalar")
                        .HasForeignKey("AboneKsBilgiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abone");
                });

            modelBuilder.Entity("ahlatciapp.Models.AboneKsBilgi", b =>
                {
                    b.Navigation("adresler")
                        .IsRequired();

                    b.Navigation("faturalar");
                });
#pragma warning restore 612, 618
        }
    }
}
